### PR TITLE
works?

### PR DESCRIPTION
**Pull request by sebhoerl**
Unfortunately, I cannot test it:

    java.io.FileNotFoundException: /home/sebastian/idsc-frazzoli/SiouxFalls/linkSpeedData (No such file or directory)

### CODE REVIEW

**Comment by andy2804** [comment]
There is no linkSpeedData for SiouxFalls. Just comment line 90 in ScenarioServer.java and remove the argument in the call at line 105

LinkSpeedContainer lsData = LinkSpeedUtils.loadLinkSpeedData(linkSpeedDataFile);

**Comment by sebhoerl** [comment]
but then you don't want to add it as a controler listener (in the module)? i have no clue what your code does, so best is you test if this does what you want ;)

**Comment by andy2804** [comment]
Eventually this is obviously the goal. The implementation right now in the LinkSpeedCalulcator which is going to be bound just sets the speed for some particular links to 0.001 just to see if the controler uses the LinkSpeedCalculator. So if you replace line 105 by

controler.addOverridingModule(new LinkSpeedModule(events, scenario));

It should work

**Comment by sebhoerl** [comment]
Well please have a look at my changes, I removed those constructors to do a clean dependency injection

**Comment by andy2804** [comment]
Thank you for reviewing it, I will have a look at the changes in the evening!

**Comment by andy2804** [comment]
Hi Sebastian,

The provideCustomConfigurableQNetworkFactory never seems to be called and the code never executed, thus my custom linkspeedCalculator also never executes. Somehow QSim doesn't seem to use our custom implementation. I also looked at the example provided by matsim and that doesn't work for me. Any further ideas?

(you can find their example here: RunConfigurableQNetworkFactoryExample)

**Comment by sebhoerl** [comment]
I @andy2804 , you're right, the injection doesn't really go through to the QSim, once the AV package is added to MATSim, that's why it did work in my other repositories, but not here. It's a bit of an ugly fix now (9c7c634), but it should work. Let me know if there's still something wrong.

**Comment by andy2804** [comment]
Hi Sebastian!

I just tested the new injection and it works with the custom LinkSpeedCalculator, thank you very much (I wouldn't have figured out how to implement it). I had to modify the injection of the LinkSpeedProvider though, it threw null pointer exception at runtime.

**Pull request merged**
